#ifndef GUARD_CONSTANTS_ITEM_MENU_H
#define GUARD_CONSTANTS_ITEM_MENU_H

#define OPEN_BAG_ITEMS     0
#define OPEN_BAG_KEYITEMS  4
#define OPEN_BAG_POKEBALLS 1
#define OPEN_BAG_LAST      3

#define FRLG_ITEMMENULOCATION_FIELD            0
#define FRLG_ITEMMENULOCATION_PARTY            1
#define FRLG_ITEMMENULOCATION_SHOP             2
#define FRLG_ITEMMENULOCATION_ITEMPC           3
#define FRLG_ITEMMENULOCATION_PCBOX            4
#define FRLG_ITEMMENULOCATION_BATTLE           5
#define FRLG_ITEMMENULOCATION_OLD_MAN          6
#define FRLG_ITEMMENULOCATION_TTVSCR_STATUS    7
#define FRLG_ITEMMENULOCATION_TTVSCR_CATCHING  8
#define FRLG_ITEMMENULOCATION_TTVSCR_REGISTER  9
#define FRLG_ITEMMENULOCATION_TTVSCR_TMS      10
#define FRLG_ITEMMENULOCATION_LAST            11

#define FRLG_ITEMMENUACTION_USE           0
#define FRLG_ITEMMENUACTION_TOSS          1
#define FRLG_ITEMMENUACTION_REGISTER      2
#define FRLG_ITEMMENUACTION_GIVE          3
#define FRLG_ITEMMENUACTION_CANCEL        4
#define FRLG_ITEMMENUACTION_BATTLE_USE    5
#define FRLG_ITEMMENUACTION_CHECK         6
#define FRLG_ITEMMENUACTION_OPEN          7
#define FRLG_ITEMMENUACTION_OPEN_BERRIES  8
#define FRLG_ITEMMENUACTION_WALK          9
#define FRLG_ITEMMENUACTION_DESELECT     10
#define FRLG_ITEMMENUACTION_DUMMY        11

#endif //GUARD_CONSTANTS_ITEM_MENU_H
