#ifndef GUARD_CONSTANTS_LAYOUTS_H
#define GUARD_CONSTANTS_LAYOUTS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/layouts/layouts.json
//

#define LAYOUT_ROUTE1 1
#define LAYOUT_PALLET_TOWN 2
#define LAYOUT_PALLET_TOWN_PLAYERS_HOUSE_1F 3
#define LAYOUT_PALLET_TOWN_PLAYERS_HOUSE_2F 4
#define LAYOUT_PALLET_TOWN_RIVALS_HOUSE_1F 5
#define LAYOUT_PROFESSOR_OAKS_LAB 6
#define LAYOUT_VIRIDIAN_CITY 7

#endif // GUARD_CONSTANTS_LAYOUTS_H
