Text_PictureBookShelf:
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"

Text_Food::
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"

Text_Dresser::
	.string "It's a nicely made dresser.\n"
	.string "It will hold a lot of stuff.$"

Text_Kitchen::
	.string "It smells delicious!\n"
	.string "Somebody's been cooking here.$"

Text_Computer::
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"

Text_Cup::
	.string "It's a cup with a POKéMON mark\n"
	.string "on it.$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Dishes and plates are neatly\n"
	.string "lined up.$"

Text_Painting::
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"
