#ifndef GUARD_CHARACTER_CUSTOMIZATION_H
#define GUARD_CHARACTER_CUSTOMIZATION_H

enum HatColors
{
    HAT_COLOR_GREEN,
    HAT_COLOR_RED,
    HAT_COLOR_BLUE,
    HAT_COLOR_YELLOW,
    HAT_COLOR_PURPLE,
    HAT_COLOR_PINK,
    HAT_COLOR_COUNT,
};

void UpdateCharacterPalette(u32 offset);

#endif // GUARD_CHARACTER_CUSTOMIZATION_H